AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation first template'
Parameters:
  myVPC:
    Type: String
    Description: VPCid
  mySubnet:
    Type: String
    Description: Subnetid
Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: "my ec2 security group"
      GroupName: "Myec2SG"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0    
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
       - IpProtocol: tcp
         FromPort: 80
         ToPort: 80
         CidrIp: 0.0.0.0/0
      VpcId: !Ref myVPC     
  MyEC2Instance: 
        Type: AWS::EC2::Instance
        DependsOn: MySecurityGroup   
        Properties: 
            InstanceType: "t2.micro"
            ImageId: "ami-0d5eff06f840b45e9"
            KeyName: "Somufirst"
            BlockDeviceMappings: 
            - DeviceName: "/dev/sdm"
              Ebs: 
                VolumeType: "io1"
                Iops: "200"
                DeleteOnTermination: "false"
                VolumeSize: "20"
            - DeviceName: "/dev/sdk"
              NoDevice: {}
            NetworkInterfaces: 
              - AssociatePublicIpAddress: "true"
                DeviceIndex: "0"
                GroupSet: [!Ref MySecurityGroup]
                SubnetId: !Ref mySubnet